//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.swift.xsd.camt_025_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ReceiptV03 complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ReceiptV03"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MsgHdr" type="{urn:swift:xsd:camt.025.001.03}CAMT025MessageHeader2CMA"/&gt;
 *         &lt;element name="RctDtls" type="{urn:swift:xsd:camt.025.001.03}Receipt1" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReceiptV03", propOrder = {
        "msgHdr",
        "rctDtls"
})
public class ReceiptV03 {

    @XmlElement(name = "MsgHdr", required = true)
    protected CAMT025MessageHeader2CMA msgHdr;
    @XmlElement(name = "RctDtls", required = true)
    protected List<Receipt1> rctDtls;

    /**
     * Gets the value of the msgHdr property.
     *
     * @return possible object is
     * {@link CAMT025MessageHeader2CMA }
     */
    public CAMT025MessageHeader2CMA getMsgHdr() {
        return msgHdr;
    }

    /**
     * Sets the value of the msgHdr property.
     *
     * @param value allowed object is
     *              {@link CAMT025MessageHeader2CMA }
     */
    public void setMsgHdr(CAMT025MessageHeader2CMA value) {
        this.msgHdr = value;
    }

    /**
     * Gets the value of the rctDtls property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rctDtls property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRctDtls().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Receipt1 }
     */
    public List<Receipt1> getRctDtls() {
        if (rctDtls == null) {
            rctDtls = new ArrayList<Receipt1>();
        }
        return this.rctDtls;
    }

}
