//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.iso.std.iso._20022.tech.xsd.pacs_009_001;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PACS009LclInstrm.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PACS009LclInstrm"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="RTGS_FICT"/&gt;
 *     &lt;enumeration value="RTGS_RETN"/&gt;
 *     &lt;enumeration value="RTGS_OACT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "PACS009LclInstrm")
@XmlEnum
public enum PACS009LclInstrm {

    RTGS_FICT,
    RTGS_RETN,
    RTGS_OACT;

    public static PACS009LclInstrm fromValue(String v) {
        return valueOf(v);
    }

    public String value() {
        return name();
    }

}
