//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.iso.std.iso._20022.tech.xsd.camt_052_001;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for CAMT052RemittanceLocation2 complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CAMT052RemittanceLocation2"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RmtId" type="{urn:iso:std:iso:20022:tech:xsd:camt.052.001.04}Max35Text" minOccurs="0"/&gt;
 *         &lt;element name="RmtLctnMtd" type="{urn:iso:std:iso:20022:tech:xsd:camt.052.001.04}RemittanceLocationMethod2Code" minOccurs="0"/&gt;
 *         &lt;element name="RmtLctnElctrncAdr" type="{urn:iso:std:iso:20022:tech:xsd:camt.052.001.04}Max2048Text" minOccurs="0"/&gt;
 *         &lt;element name="RmtLctnPstlAdr" type="{urn:iso:std:iso:20022:tech:xsd:camt.052.001.04}CAMT052NameAndAddress10" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CAMT052RemittanceLocation2", propOrder = {
        "rmtId",
        "rmtLctnMtd",
        "rmtLctnElctrncAdr",
        "rmtLctnPstlAdr"
})
public class CAMT052RemittanceLocation2 {

    @XmlElement(name = "RmtId")
    protected String rmtId;
    @XmlElement(name = "RmtLctnMtd")
    @XmlSchemaType(name = "string")
    protected RemittanceLocationMethod2Code rmtLctnMtd;
    @XmlElement(name = "RmtLctnElctrncAdr")
    protected String rmtLctnElctrncAdr;
    @XmlElement(name = "RmtLctnPstlAdr")
    protected CAMT052NameAndAddress10 rmtLctnPstlAdr;

    /**
     * Gets the value of the rmtId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRmtId() {
        return rmtId;
    }

    /**
     * Sets the value of the rmtId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRmtId(String value) {
        this.rmtId = value;
    }

    /**
     * Gets the value of the rmtLctnMtd property.
     *
     * @return possible object is
     * {@link RemittanceLocationMethod2Code }
     */
    public RemittanceLocationMethod2Code getRmtLctnMtd() {
        return rmtLctnMtd;
    }

    /**
     * Sets the value of the rmtLctnMtd property.
     *
     * @param value allowed object is
     *              {@link RemittanceLocationMethod2Code }
     */
    public void setRmtLctnMtd(RemittanceLocationMethod2Code value) {
        this.rmtLctnMtd = value;
    }

    /**
     * Gets the value of the rmtLctnElctrncAdr property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRmtLctnElctrncAdr() {
        return rmtLctnElctrncAdr;
    }

    /**
     * Sets the value of the rmtLctnElctrncAdr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRmtLctnElctrncAdr(String value) {
        this.rmtLctnElctrncAdr = value;
    }

    /**
     * Gets the value of the rmtLctnPstlAdr property.
     *
     * @return possible object is
     * {@link CAMT052NameAndAddress10 }
     */
    public CAMT052NameAndAddress10 getRmtLctnPstlAdr() {
        return rmtLctnPstlAdr;
    }

    /**
     * Sets the value of the rmtLctnPstlAdr property.
     *
     * @param value allowed object is
     *              {@link CAMT052NameAndAddress10 }
     */
    public void setRmtLctnPstlAdr(CAMT052NameAndAddress10 value) {
        this.rmtLctnPstlAdr = value;
    }

}
