//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.swift.xsd.camt_018_001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the swift.xsd.camt_018_001 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:swift:xsd:camt.018.001.03", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: swift.xsd.camt_018_001
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link BusinessDayCriteria1 }
     */
    public BusinessDayCriteria1 createBusinessDayCriteria1() {
        return new BusinessDayCriteria1();
    }

    /**
     * Create an instance of {@link BusinessDayCriteria2Choice }
     */
    public BusinessDayCriteria2Choice createBusinessDayCriteria2Choice() {
        return new BusinessDayCriteria2Choice();
    }

    /**
     * Create an instance of {@link BusinessDayQuery1 }
     */
    public BusinessDayQuery1 createBusinessDayQuery1() {
        return new BusinessDayQuery1();
    }

    /**
     * Create an instance of {@link BusinessDayQuery1CMA }
     */
    public BusinessDayQuery1CMA createBusinessDayQuery1CMA() {
        return new BusinessDayQuery1CMA();
    }

    /**
     * Create an instance of {@link BusinessDayReturnCriteria2 }
     */
    public BusinessDayReturnCriteria2 createBusinessDayReturnCriteria2() {
        return new BusinessDayReturnCriteria2();
    }

    /**
     * Create an instance of {@link BusinessDaySearchCriteria1 }
     */
    public BusinessDaySearchCriteria1 createBusinessDaySearchCriteria1() {
        return new BusinessDaySearchCriteria1();
    }

    /**
     * Create an instance of {@link DateTimePeriodChoice }
     */
    public DateTimePeriodChoice createDateTimePeriodChoice() {
        return new DateTimePeriodChoice();
    }

    /**
     * Create an instance of {@link DateTimePeriodDetails }
     */
    public DateTimePeriodDetails createDateTimePeriodDetails() {
        return new DateTimePeriodDetails();
    }

    /**
     * Create an instance of {@link GETBUSINESSDAYPERIOD01 }
     */
    public GETBUSINESSDAYPERIOD01 createGETBUSINESSDAYPERIOD01() {
        return new GETBUSINESSDAYPERIOD01();
    }

    /**
     * Create an instance of {@link RequestType2Choice }
     */
    public RequestType2Choice createRequestType2Choice() {
        return new RequestType2Choice();
    }

    /**
     * Create an instance of {@link GenericIdentification1 }
     */
    public GenericIdentification1 createGenericIdentification1() {
        return new GenericIdentification1();
    }

    /**
     * Create an instance of {@link CAMT018MessageHeader2CMA }
     */
    public CAMT018MessageHeader2CMA createCAMT018MessageHeader2CMA() {
        return new CAMT018MessageHeader2CMA();
    }

    /**
     * Create an instance of {@link GetBusinessDayInformationV03 }
     */
    public GetBusinessDayInformationV03 createGetBusinessDayInformationV03() {
        return new GetBusinessDayInformationV03();
    }

    /**
     * Create an instance of {@link GetBusinessDayInformationV03CMA }
     */
    public GetBusinessDayInformationV03CMA createGetBusinessDayInformationV03CMA() {
        return new GetBusinessDayInformationV03CMA();
    }

    /**
     * Create an instance of {@link MarketInfrastructureIdentification1Choice }
     */
    public MarketInfrastructureIdentification1Choice createMarketInfrastructureIdentification1Choice() {
        return new MarketInfrastructureIdentification1Choice();
    }

    /**
     * Create an instance of {@link MessageHeader2 }
     */
    public MessageHeader2 createMessageHeader2() {
        return new MessageHeader2();
    }

    /**
     * Create an instance of {@link GETBUSDAYPERMessageHeader01 }
     */
    public GETBUSDAYPERMessageHeader01 createGETBUSDAYPERMessageHeader01() {
        return new GETBUSDAYPERMessageHeader01();
    }

    /**
     * Create an instance of {@link GETBUSDAYPERCAMT018RequestType2Choice01 }
     */
    public GETBUSDAYPERCAMT018RequestType2Choice01 createGETBUSDAYPERCAMT018RequestType2Choice01() {
        return new GETBUSDAYPERCAMT018RequestType2Choice01();
    }

    /**
     * Create an instance of {@link SystemEventType2Choice }
     */
    public SystemEventType2Choice createSystemEventType2Choice() {
        return new SystemEventType2Choice();
    }

    /**
     * Create an instance of {@link SystemIdentification2Choice }
     */
    public SystemIdentification2Choice createSystemIdentification2Choice() {
        return new SystemIdentification2Choice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = "urn:swift:xsd:camt.018.001.03", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
