//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:swift:saa:xsd:saa.2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package iso20022.wrapper;
