//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.iso.std.iso._20022.tech.xsd.pacs_002_001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the iso.std.iso._20022.tech.xsd.pacs_002_001 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iso.std.iso._20022.tech.xsd.pacs_002_001
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice }
     */
    public AccountIdentification4Choice createAccountIdentification4Choice() {
        return new AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice }
     */
    public AccountSchemeName1Choice createAccountSchemeName1Choice() {
        return new AccountSchemeName1Choice();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link AdditionalTransactionInformation }
     */
    public AdditionalTransactionInformation createAdditionalTransactionInformation() {
        return new AdditionalTransactionInformation();
    }

    /**
     * Create an instance of {@link AmendmentInformationDetails8 }
     */
    public AmendmentInformationDetails8 createAmendmentInformationDetails8() {
        return new AmendmentInformationDetails8();
    }

    /**
     * Create an instance of {@link AmountType3Choice }
     */
    public AmountType3Choice createAmountType3Choice() {
        return new AmountType3Choice();
    }

    /**
     * Create an instance of {@link BillerTransactionInformation }
     */
    public BillerTransactionInformation createBillerTransactionInformation() {
        return new BillerTransactionInformation();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification5 }
     */
    public BranchAndFinancialInstitutionIdentification5 createBranchAndFinancialInstitutionIdentification5() {
        return new BranchAndFinancialInstitutionIdentification5();
    }

    /**
     * Create an instance of {@link PACS002BranchAndFinancialInstitutionIdentificationCMA1 }
     */
    public PACS002BranchAndFinancialInstitutionIdentificationCMA1 createPACS002BranchAndFinancialInstitutionIdentificationCMA1() {
        return new PACS002BranchAndFinancialInstitutionIdentificationCMA1();
    }

    /**
     * Create an instance of {@link CashAccount24 }
     */
    public CashAccount24 createCashAccount24() {
        return new CashAccount24();
    }

    /**
     * Create an instance of {@link PACS002CashAccount24CMA1 }
     */
    public PACS002CashAccount24CMA1 createPACS002CashAccount24CMA1() {
        return new PACS002CashAccount24CMA1();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice }
     */
    public CashAccountType2Choice createCashAccountType2Choice() {
        return new CashAccountType2Choice();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice }
     */
    public CategoryPurpose1Choice createCategoryPurpose1Choice() {
        return new CategoryPurpose1Choice();
    }

    /**
     * Create an instance of {@link Charges2 }
     */
    public Charges2 createCharges2() {
        return new Charges2();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentificationCMA1 }
     */
    public BranchAndFinancialInstitutionIdentificationCMA1 createBranchAndFinancialInstitutionIdentificationCMA1() {
        return new BranchAndFinancialInstitutionIdentificationCMA1();
    }

    /**
     * Create an instance of {@link BranchData2 }
     */
    public BranchData2 createBranchData2() {
        return new BranchData2();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification2Choice }
     */
    public ClearingSystemIdentification2Choice createClearingSystemIdentification2Choice() {
        return new ClearingSystemIdentification2Choice();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification3Choice }
     */
    public ClearingSystemIdentification3Choice createClearingSystemIdentification3Choice() {
        return new ClearingSystemIdentification3Choice();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link ContactDetails2 }
     */
    public ContactDetails2 createContactDetails2() {
        return new ContactDetails2();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation2 }
     */
    public CreditorReferenceInformation2 createCreditorReferenceInformation2() {
        return new CreditorReferenceInformation2();
    }

    /**
     * Create an instance of {@link CreditorReferenceType1Choice }
     */
    public CreditorReferenceType1Choice createCreditorReferenceType1Choice() {
        return new CreditorReferenceType1Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceType2 }
     */
    public CreditorReferenceType2 createCreditorReferenceType2() {
        return new CreditorReferenceType2();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth }
     */
    public DateAndPlaceOfBirth createDateAndPlaceOfBirth() {
        return new DateAndPlaceOfBirth();
    }

    /**
     * Create an instance of {@link DiscountAmountAndType1 }
     */
    public DiscountAmountAndType1 createDiscountAmountAndType1() {
        return new DiscountAmountAndType1();
    }

    /**
     * Create an instance of {@link DiscountAmountType1Choice }
     */
    public DiscountAmountType1Choice createDiscountAmountType1Choice() {
        return new DiscountAmountType1Choice();
    }

    /**
     * Create an instance of {@link DocumentAdjustment1 }
     */
    public DocumentAdjustment1 createDocumentAdjustment1() {
        return new DocumentAdjustment1();
    }

    /**
     * Create an instance of {@link EquivalentAmount2 }
     */
    public EquivalentAmount2 createEquivalentAmount2() {
        return new EquivalentAmount2();
    }

    /**
     * Create an instance of {@link FIToFIPaymentStatusReportV05 }
     */
    public FIToFIPaymentStatusReportV05 createFIToFIPaymentStatusReportV05() {
        return new FIToFIPaymentStatusReportV05();
    }

    /**
     * Create an instance of {@link FIToFIPaymentStatusReportV05CMA }
     */
    public FIToFIPaymentStatusReportV05CMA createFIToFIPaymentStatusReportV05CMA() {
        return new FIToFIPaymentStatusReportV05CMA();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification8 }
     */
    public FinancialInstitutionIdentification8 createFinancialInstitutionIdentification8() {
        return new FinancialInstitutionIdentification8();
    }

    /**
     * Create an instance of {@link GenericAccountIdentificationCMA1 }
     */
    public GenericAccountIdentificationCMA1 createGenericAccountIdentificationCMA1() {
        return new GenericAccountIdentificationCMA1();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link GroupHeader53 }
     */
    public GroupHeader53 createGroupHeader53() {
        return new GroupHeader53();
    }

    /**
     * Create an instance of {@link GroupHeader53CMA }
     */
    public GroupHeader53CMA createGroupHeader53CMA() {
        return new GroupHeader53CMA();
    }

    /**
     * Create an instance of {@link PACS002LocalInstrument2Choice }
     */
    public PACS002LocalInstrument2Choice createPACS002LocalInstrument2Choice() {
        return new PACS002LocalInstrument2Choice();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice }
     */
    public LocalInstrument2Choice createLocalInstrument2Choice() {
        return new LocalInstrument2Choice();
    }

    /**
     * Create an instance of {@link MandateRelatedInformation8 }
     */
    public MandateRelatedInformation8 createMandateRelatedInformation8() {
        return new MandateRelatedInformation8();
    }

    /**
     * Create an instance of {@link NumberOfTransactionsPerStatus3 }
     */
    public NumberOfTransactionsPerStatus3 createNumberOfTransactionsPerStatus3() {
        return new NumberOfTransactionsPerStatus3();
    }

    /**
     * Create an instance of {@link OrganisationIdentification8 }
     */
    public OrganisationIdentification8 createOrganisationIdentification8() {
        return new OrganisationIdentification8();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link OriginalGroupHeader1 }
     */
    public OriginalGroupHeader1 createOriginalGroupHeader1() {
        return new OriginalGroupHeader1();
    }

    /**
     * Create an instance of {@link OriginalGroupHeaderCMA1 }
     */
    public OriginalGroupHeaderCMA1 createOriginalGroupHeaderCMA1() {
        return new OriginalGroupHeaderCMA1();
    }

    /**
     * Create an instance of {@link OriginalTransactionReference16 }
     */
    public OriginalTransactionReference16 createOriginalTransactionReference16() {
        return new OriginalTransactionReference16();
    }

    /**
     * Create an instance of {@link Party11Choice }
     */
    public Party11Choice createParty11Choice() {
        return new Party11Choice();
    }

    /**
     * Create an instance of {@link PartyIdentification43 }
     */
    public PartyIdentification43 createPartyIdentification43() {
        return new PartyIdentification43();
    }

    /**
     * Create an instance of {@link PaymentTransaction43 }
     */
    public PaymentTransaction43 createPaymentTransaction43() {
        return new PaymentTransaction43();
    }

    /**
     * Create an instance of {@link PaymentTransaction33CMA }
     */
    public PaymentTransaction33CMA createPaymentTransaction33CMA() {
        return new PaymentTransaction33CMA();
    }

    /**
     * Create an instance of {@link PACS002PaymentTypeInformation25 }
     */
    public PACS002PaymentTypeInformation25 createPACS002PaymentTypeInformation25() {
        return new PACS002PaymentTypeInformation25();
    }

    /**
     * Create an instance of {@link PersonIdentification5 }
     */
    public PersonIdentification5 createPersonIdentification5() {
        return new PersonIdentification5();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link PostalAddress6 }
     */
    public PostalAddress6 createPostalAddress6() {
        return new PostalAddress6();
    }

    /**
     * Create an instance of {@link ReferredDocumentInformation3 }
     */
    public ReferredDocumentInformation3 createReferredDocumentInformation3() {
        return new ReferredDocumentInformation3();
    }

    /**
     * Create an instance of {@link ReferredDocumentType1Choice }
     */
    public ReferredDocumentType1Choice createReferredDocumentType1Choice() {
        return new ReferredDocumentType1Choice();
    }

    /**
     * Create an instance of {@link ReferredDocumentType2 }
     */
    public ReferredDocumentType2 createReferredDocumentType2() {
        return new ReferredDocumentType2();
    }

    /**
     * Create an instance of {@link RemittanceAmount2 }
     */
    public RemittanceAmount2 createRemittanceAmount2() {
        return new RemittanceAmount2();
    }

    /**
     * Create an instance of {@link RemittanceInformation7Ustrd }
     */
    public RemittanceInformation7Ustrd createRemittanceInformation7Ustrd() {
        return new RemittanceInformation7Ustrd();
    }

    /**
     * Create an instance of {@link ServiceLevel8Choice }
     */
    public ServiceLevel8Choice createServiceLevel8Choice() {
        return new ServiceLevel8Choice();
    }

    /**
     * Create an instance of {@link SettlementInstruction4 }
     */
    public SettlementInstruction4 createSettlementInstruction4() {
        return new SettlementInstruction4();
    }

    /**
     * Create an instance of {@link StatusReason6Choice }
     */
    public StatusReason6Choice createStatusReason6Choice() {
        return new StatusReason6Choice();
    }

    /**
     * Create an instance of {@link StatusReason6ChoiceCMA1 }
     */
    public StatusReason6ChoiceCMA1 createStatusReason6ChoiceCMA1() {
        return new StatusReason6ChoiceCMA1();
    }

    /**
     * Create an instance of {@link StatusReasonInformation9 }
     */
    public StatusReasonInformation9 createStatusReasonInformation9() {
        return new StatusReasonInformation9();
    }

    /**
     * Create an instance of {@link StatusReasonInformation9CMA1 }
     */
    public StatusReasonInformation9CMA1 createStatusReasonInformation9CMA1() {
        return new StatusReasonInformation9CMA1();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation9 }
     */
    public StructuredRemittanceInformation9 createStructuredRemittanceInformation9() {
        return new StructuredRemittanceInformation9();
    }

    /**
     * Create an instance of {@link SupplementaryData1CMA1 }
     */
    public SupplementaryData1CMA1 createSupplementaryData1CMA1() {
        return new SupplementaryData1CMA1();
    }

    /**
     * Create an instance of {@link SupplementaryDataEnvelope1 }
     */
    public SupplementaryDataEnvelope1 createSupplementaryDataEnvelope1() {
        return new SupplementaryDataEnvelope1();
    }

    /**
     * Create an instance of {@link SupplementaryDataEnvelopeCMA2 }
     */
    public SupplementaryDataEnvelopeCMA2 createSupplementaryDataEnvelopeCMA2() {
        return new SupplementaryDataEnvelopeCMA2();
    }

    /**
     * Create an instance of {@link TaxAmountAndType1 }
     */
    public TaxAmountAndType1 createTaxAmountAndType1() {
        return new TaxAmountAndType1();
    }

    /**
     * Create an instance of {@link TaxAmountType1Choice }
     */
    public TaxAmountType1Choice createTaxAmountType1Choice() {
        return new TaxAmountType1Choice();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentificationCMA1 }
     */
    public FinancialInstitutionIdentificationCMA1 createFinancialInstitutionIdentificationCMA1() {
        return new FinancialInstitutionIdentificationCMA1();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
