//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.iso.std.iso._20022.tech.xsd.pacs_002_001;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OriginalTransactionReference16 complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OriginalTransactionReference16"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IntrBkSttlmAmt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}ActiveOrHistoricCurrencyAndAmount" minOccurs="0"/&gt;
 *         &lt;element name="IntrBkSttlmDt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}ISODate" minOccurs="0"/&gt;
 *         &lt;element name="PmtTpInf" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}PACS002PaymentTypeInformation25" minOccurs="0"/&gt;
 *         &lt;element name="RmtInf" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}RemittanceInformation7Ustrd" minOccurs="0"/&gt;
 *         &lt;element name="Dbtr" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}PartyIdentification43" minOccurs="0"/&gt;
 *         &lt;element name="DbtrAcct" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}PACS002CashAccount24CMA1" minOccurs="0"/&gt;
 *         &lt;element name="DbtrAgt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}PACS002BranchAndFinancialInstitutionIdentificationCMA1" minOccurs="0"/&gt;
 *         &lt;element name="DbtrAgtAcct" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}CashAccount24" minOccurs="0"/&gt;
 *         &lt;element name="CdtrAgt" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}PACS002BranchAndFinancialInstitutionIdentificationCMA1" minOccurs="0"/&gt;
 *         &lt;element name="CdtrAgtAcct" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}CashAccount24" minOccurs="0"/&gt;
 *         &lt;element name="Cdtr" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}PartyIdentification43" minOccurs="0"/&gt;
 *         &lt;element name="CdtrAcct" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}PACS002CashAccount24CMA1" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OriginalTransactionReference16", propOrder = {
        "intrBkSttlmAmt",
        "intrBkSttlmDt",
        "pmtTpInf",
        "rmtInf",
        "dbtr",
        "dbtrAcct",
        "dbtrAgt",
        "dbtrAgtAcct",
        "cdtrAgt",
        "cdtrAgtAcct",
        "cdtr",
        "cdtrAcct"
})
public class OriginalTransactionReference16 {

    @XmlElement(name = "IntrBkSttlmAmt")
    protected ActiveOrHistoricCurrencyAndAmount intrBkSttlmAmt;
    @XmlElement(name = "IntrBkSttlmDt")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar intrBkSttlmDt;
    @XmlElement(name = "PmtTpInf")
    protected PACS002PaymentTypeInformation25 pmtTpInf;
    @XmlElement(name = "RmtInf")
    protected RemittanceInformation7Ustrd rmtInf;
    @XmlElement(name = "Dbtr")
    protected PartyIdentification43 dbtr;
    @XmlElement(name = "DbtrAcct")
    protected PACS002CashAccount24CMA1 dbtrAcct;
    @XmlElement(name = "DbtrAgt")
    protected PACS002BranchAndFinancialInstitutionIdentificationCMA1 dbtrAgt;
    @XmlElement(name = "DbtrAgtAcct")
    protected CashAccount24 dbtrAgtAcct;
    @XmlElement(name = "CdtrAgt")
    protected PACS002BranchAndFinancialInstitutionIdentificationCMA1 cdtrAgt;
    @XmlElement(name = "CdtrAgtAcct")
    protected CashAccount24 cdtrAgtAcct;
    @XmlElement(name = "Cdtr")
    protected PartyIdentification43 cdtr;
    @XmlElement(name = "CdtrAcct")
    protected PACS002CashAccount24CMA1 cdtrAcct;

    /**
     * Gets the value of the intrBkSttlmAmt property.
     *
     * @return possible object is
     * {@link ActiveOrHistoricCurrencyAndAmount }
     */
    public ActiveOrHistoricCurrencyAndAmount getIntrBkSttlmAmt() {
        return intrBkSttlmAmt;
    }

    /**
     * Sets the value of the intrBkSttlmAmt property.
     *
     * @param value allowed object is
     *              {@link ActiveOrHistoricCurrencyAndAmount }
     */
    public void setIntrBkSttlmAmt(ActiveOrHistoricCurrencyAndAmount value) {
        this.intrBkSttlmAmt = value;
    }

    /**
     * Gets the value of the intrBkSttlmDt property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getIntrBkSttlmDt() {
        return intrBkSttlmDt;
    }

    /**
     * Sets the value of the intrBkSttlmDt property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setIntrBkSttlmDt(XMLGregorianCalendar value) {
        this.intrBkSttlmDt = value;
    }

    /**
     * Gets the value of the pmtTpInf property.
     *
     * @return possible object is
     * {@link PACS002PaymentTypeInformation25 }
     */
    public PACS002PaymentTypeInformation25 getPmtTpInf() {
        return pmtTpInf;
    }

    /**
     * Sets the value of the pmtTpInf property.
     *
     * @param value allowed object is
     *              {@link PACS002PaymentTypeInformation25 }
     */
    public void setPmtTpInf(PACS002PaymentTypeInformation25 value) {
        this.pmtTpInf = value;
    }

    /**
     * Gets the value of the rmtInf property.
     *
     * @return possible object is
     * {@link RemittanceInformation7Ustrd }
     */
    public RemittanceInformation7Ustrd getRmtInf() {
        return rmtInf;
    }

    /**
     * Sets the value of the rmtInf property.
     *
     * @param value allowed object is
     *              {@link RemittanceInformation7Ustrd }
     */
    public void setRmtInf(RemittanceInformation7Ustrd value) {
        this.rmtInf = value;
    }

    /**
     * Gets the value of the dbtr property.
     *
     * @return possible object is
     * {@link PartyIdentification43 }
     */
    public PartyIdentification43 getDbtr() {
        return dbtr;
    }

    /**
     * Sets the value of the dbtr property.
     *
     * @param value allowed object is
     *              {@link PartyIdentification43 }
     */
    public void setDbtr(PartyIdentification43 value) {
        this.dbtr = value;
    }

    /**
     * Gets the value of the dbtrAcct property.
     *
     * @return possible object is
     * {@link PACS002CashAccount24CMA1 }
     */
    public PACS002CashAccount24CMA1 getDbtrAcct() {
        return dbtrAcct;
    }

    /**
     * Sets the value of the dbtrAcct property.
     *
     * @param value allowed object is
     *              {@link PACS002CashAccount24CMA1 }
     */
    public void setDbtrAcct(PACS002CashAccount24CMA1 value) {
        this.dbtrAcct = value;
    }

    /**
     * Gets the value of the dbtrAgt property.
     *
     * @return possible object is
     * {@link PACS002BranchAndFinancialInstitutionIdentificationCMA1 }
     */
    public PACS002BranchAndFinancialInstitutionIdentificationCMA1 getDbtrAgt() {
        return dbtrAgt;
    }

    /**
     * Sets the value of the dbtrAgt property.
     *
     * @param value allowed object is
     *              {@link PACS002BranchAndFinancialInstitutionIdentificationCMA1 }
     */
    public void setDbtrAgt(PACS002BranchAndFinancialInstitutionIdentificationCMA1 value) {
        this.dbtrAgt = value;
    }

    /**
     * Gets the value of the dbtrAgtAcct property.
     *
     * @return possible object is
     * {@link CashAccount24 }
     */
    public CashAccount24 getDbtrAgtAcct() {
        return dbtrAgtAcct;
    }

    /**
     * Sets the value of the dbtrAgtAcct property.
     *
     * @param value allowed object is
     *              {@link CashAccount24 }
     */
    public void setDbtrAgtAcct(CashAccount24 value) {
        this.dbtrAgtAcct = value;
    }

    /**
     * Gets the value of the cdtrAgt property.
     *
     * @return possible object is
     * {@link PACS002BranchAndFinancialInstitutionIdentificationCMA1 }
     */
    public PACS002BranchAndFinancialInstitutionIdentificationCMA1 getCdtrAgt() {
        return cdtrAgt;
    }

    /**
     * Sets the value of the cdtrAgt property.
     *
     * @param value allowed object is
     *              {@link PACS002BranchAndFinancialInstitutionIdentificationCMA1 }
     */
    public void setCdtrAgt(PACS002BranchAndFinancialInstitutionIdentificationCMA1 value) {
        this.cdtrAgt = value;
    }

    /**
     * Gets the value of the cdtrAgtAcct property.
     *
     * @return possible object is
     * {@link CashAccount24 }
     */
    public CashAccount24 getCdtrAgtAcct() {
        return cdtrAgtAcct;
    }

    /**
     * Sets the value of the cdtrAgtAcct property.
     *
     * @param value allowed object is
     *              {@link CashAccount24 }
     */
    public void setCdtrAgtAcct(CashAccount24 value) {
        this.cdtrAgtAcct = value;
    }

    /**
     * Gets the value of the cdtr property.
     *
     * @return possible object is
     * {@link PartyIdentification43 }
     */
    public PartyIdentification43 getCdtr() {
        return cdtr;
    }

    /**
     * Sets the value of the cdtr property.
     *
     * @param value allowed object is
     *              {@link PartyIdentification43 }
     */
    public void setCdtr(PartyIdentification43 value) {
        this.cdtr = value;
    }

    /**
     * Gets the value of the cdtrAcct property.
     *
     * @return possible object is
     * {@link PACS002CashAccount24CMA1 }
     */
    public PACS002CashAccount24CMA1 getCdtrAcct() {
        return cdtrAcct;
    }

    /**
     * Sets the value of the cdtrAcct property.
     *
     * @param value allowed object is
     *              {@link PACS002CashAccount24CMA1 }
     */
    public void setCdtrAcct(PACS002CashAccount24CMA1 value) {
        this.cdtrAcct = value;
    }

}
