//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.iso.std.iso._20022.tech.xsd.pacs_002_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SupplementaryDataEnvelopeCMA2 complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SupplementaryDataEnvelopeCMA2"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AddtlTxInf" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}AdditionalTransactionInformation"/&gt;
 *         &lt;element name="BlrTxInf" type="{urn:iso:std:iso:20022:tech:xsd:pacs.002.001.05}BillerTransactionInformation" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplementaryDataEnvelopeCMA2", propOrder = {
        "addtlTxInf",
        "blrTxInf"
})
public class SupplementaryDataEnvelopeCMA2 {

    @XmlElement(name = "AddtlTxInf", required = true)
    protected AdditionalTransactionInformation addtlTxInf;
    @XmlElement(name = "BlrTxInf")
    protected BillerTransactionInformation blrTxInf;

    /**
     * Gets the value of the addtlTxInf property.
     *
     * @return possible object is
     * {@link AdditionalTransactionInformation }
     */
    public AdditionalTransactionInformation getAddtlTxInf() {
        return addtlTxInf;
    }

    /**
     * Sets the value of the addtlTxInf property.
     *
     * @param value allowed object is
     *              {@link AdditionalTransactionInformation }
     */
    public void setAddtlTxInf(AdditionalTransactionInformation value) {
        this.addtlTxInf = value;
    }

    /**
     * Gets the value of the blrTxInf property.
     *
     * @return possible object is
     * {@link BillerTransactionInformation }
     */
    public BillerTransactionInformation getBlrTxInf() {
        return blrTxInf;
    }

    /**
     * Sets the value of the blrTxInf property.
     *
     * @param value allowed object is
     *              {@link BillerTransactionInformation }
     */
    public void setBlrTxInf(BillerTransactionInformation value) {
        this.blrTxInf = value;
    }

}
