//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.06 at 11:07:57 AM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://integration.gwclient.smallsystems.cma.se/")
package com.cbl.cityrtgs.engine.dto.stpa;
