//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.iso.std.iso._20022.tech.xsd.camt_053_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for BankToCustomerStatementV04CMA complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BankToCustomerStatementV04CMA"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GrpHdr" type="{urn:iso:std:iso:20022:tech:xsd:camt.053.001.04}CAMT053GroupHeader58"/&gt;
 *         &lt;element name="Stmt" type="{urn:iso:std:iso:20022:tech:xsd:camt.053.001.04}AccountStatement4CMA" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BankToCustomerStatementV04CMA", propOrder = {
        "grpHdr",
        "stmt"
})
public class BankToCustomerStatementV04CMA {

    @XmlElement(name = "GrpHdr", required = true)
    protected CAMT053GroupHeader58 grpHdr;
    @XmlElement(name = "Stmt", required = true)
    protected List<AccountStatement4CMA> stmt;

    /**
     * Gets the value of the grpHdr property.
     *
     * @return possible object is
     * {@link CAMT053GroupHeader58 }
     */
    public CAMT053GroupHeader58 getGrpHdr() {
        return grpHdr;
    }

    /**
     * Sets the value of the grpHdr property.
     *
     * @param value allowed object is
     *              {@link CAMT053GroupHeader58 }
     */
    public void setGrpHdr(CAMT053GroupHeader58 value) {
        this.grpHdr = value;
    }

    /**
     * Gets the value of the stmt property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stmt property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStmt().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountStatement4CMA }
     */
    public List<AccountStatement4CMA> getStmt() {
        if (stmt == null) {
            stmt = new ArrayList<AccountStatement4CMA>();
        }
        return this.stmt;
    }

}
