//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.iso.std.iso._20022.tech.xsd.camt_053_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CAMT053BranchAndFinancialInstitutionIdentification5 complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CAMT053BranchAndFinancialInstitutionIdentification5"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FinInstnId" type="{urn:iso:std:iso:20022:tech:xsd:camt.053.001.04}CAMT053FinancialInstitutionIdentification8"/&gt;
 *         &lt;element name="BrnchId" type="{urn:iso:std:iso:20022:tech:xsd:camt.053.001.04}CAMT053BranchData2" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CAMT053BranchAndFinancialInstitutionIdentification5", propOrder = {
        "finInstnId",
        "brnchId"
})
public class CAMT053BranchAndFinancialInstitutionIdentification5 {

    @XmlElement(name = "FinInstnId", required = true)
    protected CAMT053FinancialInstitutionIdentification8 finInstnId;
    @XmlElement(name = "BrnchId")
    protected CAMT053BranchData2 brnchId;

    /**
     * Gets the value of the finInstnId property.
     *
     * @return possible object is
     * {@link CAMT053FinancialInstitutionIdentification8 }
     */
    public CAMT053FinancialInstitutionIdentification8 getFinInstnId() {
        return finInstnId;
    }

    /**
     * Sets the value of the finInstnId property.
     *
     * @param value allowed object is
     *              {@link CAMT053FinancialInstitutionIdentification8 }
     */
    public void setFinInstnId(CAMT053FinancialInstitutionIdentification8 value) {
        this.finInstnId = value;
    }

    /**
     * Gets the value of the brnchId property.
     *
     * @return possible object is
     * {@link CAMT053BranchData2 }
     */
    public CAMT053BranchData2 getBrnchId() {
        return brnchId;
    }

    /**
     * Sets the value of the brnchId property.
     *
     * @param value allowed object is
     *              {@link CAMT053BranchData2 }
     */
    public void setBrnchId(CAMT053BranchData2 value) {
        this.brnchId = value;
    }

}
