//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.iso.std.iso._20022.tech.xsd.camt_053_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CAMT053EntryDetails3 complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CAMT053EntryDetails3"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Btch" type="{urn:iso:std:iso:20022:tech:xsd:camt.053.001.04}CAMT053BatchInformation2" minOccurs="0"/&gt;
 *         &lt;element name="TxDtls" type="{urn:iso:std:iso:20022:tech:xsd:camt.053.001.04}CAMT053EntryTransaction4" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CAMT053EntryDetails3", propOrder = {
        "btch",
        "txDtls"
})
public class CAMT053EntryDetails3 {

    @XmlElement(name = "Btch")
    protected CAMT053BatchInformation2 btch;
    @XmlElement(name = "TxDtls")
    protected CAMT053EntryTransaction4 txDtls;

    /**
     * Gets the value of the btch property.
     *
     * @return possible object is
     * {@link CAMT053BatchInformation2 }
     */
    public CAMT053BatchInformation2 getBtch() {
        return btch;
    }

    /**
     * Sets the value of the btch property.
     *
     * @param value allowed object is
     *              {@link CAMT053BatchInformation2 }
     */
    public void setBtch(CAMT053BatchInformation2 value) {
        this.btch = value;
    }

    /**
     * Gets the value of the txDtls property.
     *
     * @return possible object is
     * {@link CAMT053EntryTransaction4 }
     */
    public CAMT053EntryTransaction4 getTxDtls() {
        return txDtls;
    }

    /**
     * Sets the value of the txDtls property.
     *
     * @param value allowed object is
     *              {@link CAMT053EntryTransaction4 }
     */
    public void setTxDtls(CAMT053EntryTransaction4 value) {
        this.txDtls = value;
    }

}
