//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.iso.std.iso._20022.tech.xsd.camt_053_001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the iso.std.iso._20022.tech.xsd.camt_053_001 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:camt.053.001.04", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iso.std.iso._20022.tech.xsd.camt_053_001
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link CAMT053AccountIdentification4Choice }
     */
    public CAMT053AccountIdentification4Choice createCAMT053AccountIdentification4Choice() {
        return new CAMT053AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link CAMT053AccountIdentification4ChoiceCMA }
     */
    public CAMT053AccountIdentification4ChoiceCMA createCAMT053AccountIdentification4ChoiceCMA() {
        return new CAMT053AccountIdentification4ChoiceCMA();
    }

    /**
     * Create an instance of {@link AccountInterest2 }
     */
    public AccountInterest2 createAccountInterest2() {
        return new AccountInterest2();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice }
     */
    public AccountSchemeName1Choice createAccountSchemeName1Choice() {
        return new AccountSchemeName1Choice();
    }

    /**
     * Create an instance of {@link AccountStatement4 }
     */
    public AccountStatement4 createAccountStatement4() {
        return new AccountStatement4();
    }

    /**
     * Create an instance of {@link AccountStatement4CMA }
     */
    public AccountStatement4CMA createAccountStatement4CMA() {
        return new AccountStatement4CMA();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAndAmount }
     */
    public ActiveCurrencyAndAmount createActiveCurrencyAndAmount() {
        return new ActiveCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAnd13DecimalAmount }
     */
    public ActiveOrHistoricCurrencyAnd13DecimalAmount createActiveOrHistoricCurrencyAnd13DecimalAmount() {
        return new ActiveOrHistoricCurrencyAnd13DecimalAmount();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link AmountAndCurrencyExchange3 }
     */
    public AmountAndCurrencyExchange3 createAmountAndCurrencyExchange3() {
        return new AmountAndCurrencyExchange3();
    }

    /**
     * Create an instance of {@link AmountAndCurrencyExchangeDetails3 }
     */
    public AmountAndCurrencyExchangeDetails3 createAmountAndCurrencyExchangeDetails3() {
        return new AmountAndCurrencyExchangeDetails3();
    }

    /**
     * Create an instance of {@link AmountAndCurrencyExchangeDetails4 }
     */
    public AmountAndCurrencyExchangeDetails4 createAmountAndCurrencyExchangeDetails4() {
        return new AmountAndCurrencyExchangeDetails4();
    }

    /**
     * Create an instance of {@link AmountAndDirection35 }
     */
    public AmountAndDirection35 createAmountAndDirection35() {
        return new AmountAndDirection35();
    }

    /**
     * Create an instance of {@link AmountRangeBoundary1 }
     */
    public AmountRangeBoundary1 createAmountRangeBoundary1() {
        return new AmountRangeBoundary1();
    }

    /**
     * Create an instance of {@link BalanceSubType1Choice }
     */
    public BalanceSubType1Choice createBalanceSubType1Choice() {
        return new BalanceSubType1Choice();
    }

    /**
     * Create an instance of {@link BalanceType12 }
     */
    public BalanceType12 createBalanceType12() {
        return new BalanceType12();
    }

    /**
     * Create an instance of {@link BalanceType5Choice }
     */
    public BalanceType5Choice createBalanceType5Choice() {
        return new BalanceType5Choice();
    }

    /**
     * Create an instance of {@link BankToCustomerStatementV04 }
     */
    public BankToCustomerStatementV04 createBankToCustomerStatementV04() {
        return new BankToCustomerStatementV04();
    }

    /**
     * Create an instance of {@link BankToCustomerStatementV04CMA }
     */
    public BankToCustomerStatementV04CMA createBankToCustomerStatementV04CMA() {
        return new BankToCustomerStatementV04CMA();
    }

    /**
     * Create an instance of {@link CAMT054BankTransactionCodeStructure4 }
     */
    public CAMT054BankTransactionCodeStructure4 createCAMT054BankTransactionCodeStructure4() {
        return new CAMT054BankTransactionCodeStructure4();
    }

    /**
     * Create an instance of {@link BankTransactionCodeStructure5 }
     */
    public BankTransactionCodeStructure5 createBankTransactionCodeStructure5() {
        return new BankTransactionCodeStructure5();
    }

    /**
     * Create an instance of {@link BankTransactionCodeStructure6 }
     */
    public BankTransactionCodeStructure6 createBankTransactionCodeStructure6() {
        return new BankTransactionCodeStructure6();
    }

    /**
     * Create an instance of {@link CAMT053BatchInformation2 }
     */
    public CAMT053BatchInformation2 createCAMT053BatchInformation2() {
        return new CAMT053BatchInformation2();
    }

    /**
     * Create an instance of {@link CAMT053BranchAndFinancialInstitutionIdentification5 }
     */
    public CAMT053BranchAndFinancialInstitutionIdentification5 createCAMT053BranchAndFinancialInstitutionIdentification5() {
        return new CAMT053BranchAndFinancialInstitutionIdentification5();
    }

    /**
     * Create an instance of {@link CAMT053BranchData2 }
     */
    public CAMT053BranchData2 createCAMT053BranchData2() {
        return new CAMT053BranchData2();
    }

    /**
     * Create an instance of {@link CardAggregated1 }
     */
    public CardAggregated1 createCardAggregated1() {
        return new CardAggregated1();
    }

    /**
     * Create an instance of {@link CAMT053CardEntry1 }
     */
    public CAMT053CardEntry1 createCAMT053CardEntry1() {
        return new CAMT053CardEntry1();
    }

    /**
     * Create an instance of {@link CardIndividualTransaction1 }
     */
    public CardIndividualTransaction1 createCardIndividualTransaction1() {
        return new CardIndividualTransaction1();
    }

    /**
     * Create an instance of {@link CardSecurityInformation1 }
     */
    public CardSecurityInformation1 createCardSecurityInformation1() {
        return new CardSecurityInformation1();
    }

    /**
     * Create an instance of {@link CardSequenceNumberRange1 }
     */
    public CardSequenceNumberRange1 createCardSequenceNumberRange1() {
        return new CardSequenceNumberRange1();
    }

    /**
     * Create an instance of {@link CAMT053CardTransaction1 }
     */
    public CAMT053CardTransaction1 createCAMT053CardTransaction1() {
        return new CAMT053CardTransaction1();
    }

    /**
     * Create an instance of {@link CardTransaction1Choice }
     */
    public CardTransaction1Choice createCardTransaction1Choice() {
        return new CardTransaction1Choice();
    }

    /**
     * Create an instance of {@link CAMT053CashAccount24 }
     */
    public CAMT053CashAccount24 createCAMT053CashAccount24() {
        return new CAMT053CashAccount24();
    }

    /**
     * Create an instance of {@link CAMT053CashAccount25 }
     */
    public CAMT053CashAccount25 createCAMT053CashAccount25() {
        return new CAMT053CashAccount25();
    }

    /**
     * Create an instance of {@link CAMT053CashAccount25CMA }
     */
    public CAMT053CashAccount25CMA createCAMT053CashAccount25CMA() {
        return new CAMT053CashAccount25CMA();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice }
     */
    public CashAccountType2Choice createCashAccountType2Choice() {
        return new CashAccountType2Choice();
    }

    /**
     * Create an instance of {@link CAMT053CashBalance3 }
     */
    public CAMT053CashBalance3 createCAMT053CashBalance3() {
        return new CAMT053CashBalance3();
    }

    /**
     * Create an instance of {@link CashBalanceAvailability2 }
     */
    public CashBalanceAvailability2 createCashBalanceAvailability2() {
        return new CashBalanceAvailability2();
    }

    /**
     * Create an instance of {@link CashBalanceAvailabilityDate1 }
     */
    public CashBalanceAvailabilityDate1 createCashBalanceAvailabilityDate1() {
        return new CashBalanceAvailabilityDate1();
    }

    /**
     * Create an instance of {@link CashDeposit1 }
     */
    public CashDeposit1 createCashDeposit1() {
        return new CashDeposit1();
    }

    /**
     * Create an instance of {@link ChargeType3Choice }
     */
    public ChargeType3Choice createChargeType3Choice() {
        return new ChargeType3Choice();
    }

    /**
     * Create an instance of {@link CAMT053Charges4 }
     */
    public CAMT053Charges4 createCAMT053Charges4() {
        return new CAMT053Charges4();
    }

    /**
     * Create an instance of {@link CAMT053ChargesRecord2 }
     */
    public CAMT053ChargesRecord2 createCAMT053ChargesRecord2() {
        return new CAMT053ChargesRecord2();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification2Choice }
     */
    public ClearingSystemIdentification2Choice createClearingSystemIdentification2Choice() {
        return new ClearingSystemIdentification2Choice();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link ContactDetails2 }
     */
    public ContactDetails2 createContactDetails2() {
        return new ContactDetails2();
    }

    /**
     * Create an instance of {@link CorporateAction9 }
     */
    public CorporateAction9 createCorporateAction9() {
        return new CorporateAction9();
    }

    /**
     * Create an instance of {@link CreditLine2 }
     */
    public CreditLine2 createCreditLine2() {
        return new CreditLine2();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation2 }
     */
    public CreditorReferenceInformation2 createCreditorReferenceInformation2() {
        return new CreditorReferenceInformation2();
    }

    /**
     * Create an instance of {@link CreditorReferenceType1Choice }
     */
    public CreditorReferenceType1Choice createCreditorReferenceType1Choice() {
        return new CreditorReferenceType1Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceType2 }
     */
    public CreditorReferenceType2 createCreditorReferenceType2() {
        return new CreditorReferenceType2();
    }

    /**
     * Create an instance of {@link CurrencyAndAmountRange2 }
     */
    public CurrencyAndAmountRange2 createCurrencyAndAmountRange2() {
        return new CurrencyAndAmountRange2();
    }

    /**
     * Create an instance of {@link CurrencyExchange5 }
     */
    public CurrencyExchange5 createCurrencyExchange5() {
        return new CurrencyExchange5();
    }

    /**
     * Create an instance of {@link CAMT053DateAndDateTimeChoice }
     */
    public CAMT053DateAndDateTimeChoice createCAMT053DateAndDateTimeChoice() {
        return new CAMT053DateAndDateTimeChoice();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth }
     */
    public DateAndPlaceOfBirth createDateAndPlaceOfBirth() {
        return new DateAndPlaceOfBirth();
    }

    /**
     * Create an instance of {@link DateOrDateTimePeriodChoice }
     */
    public DateOrDateTimePeriodChoice createDateOrDateTimePeriodChoice() {
        return new DateOrDateTimePeriodChoice();
    }

    /**
     * Create an instance of {@link DatePeriodDetails }
     */
    public DatePeriodDetails createDatePeriodDetails() {
        return new DatePeriodDetails();
    }

    /**
     * Create an instance of {@link DateTimePeriodDetails }
     */
    public DateTimePeriodDetails createDateTimePeriodDetails() {
        return new DateTimePeriodDetails();
    }

    /**
     * Create an instance of {@link DiscountAmountAndType1 }
     */
    public DiscountAmountAndType1 createDiscountAmountAndType1() {
        return new DiscountAmountAndType1();
    }

    /**
     * Create an instance of {@link DiscountAmountType1Choice }
     */
    public DiscountAmountType1Choice createDiscountAmountType1Choice() {
        return new DiscountAmountType1Choice();
    }

    /**
     * Create an instance of {@link DisplayCapabilities1 }
     */
    public DisplayCapabilities1 createDisplayCapabilities1() {
        return new DisplayCapabilities1();
    }

    /**
     * Create an instance of {@link DocumentAdjustment1 }
     */
    public DocumentAdjustment1 createDocumentAdjustment1() {
        return new DocumentAdjustment1();
    }

    /**
     * Create an instance of {@link CAMT053EntryDetails3 }
     */
    public CAMT053EntryDetails3 createCAMT053EntryDetails3() {
        return new CAMT053EntryDetails3();
    }

    /**
     * Create an instance of {@link CAMT053EntryTransaction4 }
     */
    public CAMT053EntryTransaction4 createCAMT053EntryTransaction4() {
        return new CAMT053EntryTransaction4();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link CAMT053FinancialInstitutionIdentification8 }
     */
    public CAMT053FinancialInstitutionIdentification8 createCAMT053FinancialInstitutionIdentification8() {
        return new CAMT053FinancialInstitutionIdentification8();
    }

    /**
     * Create an instance of {@link FinancialInstrumentQuantityChoice }
     */
    public FinancialInstrumentQuantityChoice createFinancialInstrumentQuantityChoice() {
        return new FinancialInstrumentQuantityChoice();
    }

    /**
     * Create an instance of {@link FromToAmountRange }
     */
    public FromToAmountRange createFromToAmountRange() {
        return new FromToAmountRange();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1 }
     */
    public GenericAccountIdentification1 createGenericAccountIdentification1() {
        return new GenericAccountIdentification1();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1CMA }
     */
    public GenericAccountIdentification1CMA createGenericAccountIdentification1CMA() {
        return new GenericAccountIdentification1CMA();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link CAMT053GenericIdentification1 }
     */
    public CAMT053GenericIdentification1 createCAMT053GenericIdentification1() {
        return new CAMT053GenericIdentification1();
    }

    /**
     * Create an instance of {@link GenericIdentification20 }
     */
    public GenericIdentification20 createGenericIdentification20() {
        return new GenericIdentification20();
    }

    /**
     * Create an instance of {@link GenericIdentification3 }
     */
    public GenericIdentification3 createGenericIdentification3() {
        return new GenericIdentification3();
    }

    /**
     * Create an instance of {@link GenericIdentification32 }
     */
    public GenericIdentification32 createGenericIdentification32() {
        return new GenericIdentification32();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link CAMT053GroupHeader58 }
     */
    public CAMT053GroupHeader58 createCAMT053GroupHeader58() {
        return new CAMT053GroupHeader58();
    }

    /**
     * Create an instance of {@link OriginalBusinessQuery1 }
     */
    public OriginalBusinessQuery1 createOriginalBusinessQuery1() {
        return new OriginalBusinessQuery1();
    }

    /**
     * Create an instance of {@link IdentificationSource3Choice }
     */
    public IdentificationSource3Choice createIdentificationSource3Choice() {
        return new IdentificationSource3Choice();
    }

    /**
     * Create an instance of {@link ImpliedCurrencyAmountRangeChoice }
     */
    public ImpliedCurrencyAmountRangeChoice createImpliedCurrencyAmountRangeChoice() {
        return new ImpliedCurrencyAmountRangeChoice();
    }

    /**
     * Create an instance of {@link InterestRecord1 }
     */
    public InterestRecord1 createInterestRecord1() {
        return new InterestRecord1();
    }

    /**
     * Create an instance of {@link InterestType1Choice }
     */
    public InterestType1Choice createInterestType1Choice() {
        return new InterestType1Choice();
    }

    /**
     * Create an instance of {@link MessageIdentification2 }
     */
    public MessageIdentification2 createMessageIdentification2() {
        return new MessageIdentification2();
    }

    /**
     * Create an instance of {@link CAMT053NameAndAddress10 }
     */
    public CAMT053NameAndAddress10 createCAMT053NameAndAddress10() {
        return new CAMT053NameAndAddress10();
    }

    /**
     * Create an instance of {@link NumberAndSumOfTransactions1 }
     */
    public NumberAndSumOfTransactions1 createNumberAndSumOfTransactions1() {
        return new NumberAndSumOfTransactions1();
    }

    /**
     * Create an instance of {@link NumberAndSumOfTransactions4 }
     */
    public NumberAndSumOfTransactions4 createNumberAndSumOfTransactions4() {
        return new NumberAndSumOfTransactions4();
    }

    /**
     * Create an instance of {@link CAMT053OrganisationIdentification8 }
     */
    public CAMT053OrganisationIdentification8 createCAMT053OrganisationIdentification8() {
        return new CAMT053OrganisationIdentification8();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link OriginalAndCurrentQuantities1 }
     */
    public OriginalAndCurrentQuantities1 createOriginalAndCurrentQuantities1() {
        return new OriginalAndCurrentQuantities1();
    }

    /**
     * Create an instance of {@link CAMT053OriginalBusinessQuery1 }
     */
    public CAMT053OriginalBusinessQuery1 createCAMT053OriginalBusinessQuery1() {
        return new CAMT053OriginalBusinessQuery1();
    }

    /**
     * Create an instance of {@link OtherIdentification1 }
     */
    public OtherIdentification1 createOtherIdentification1() {
        return new OtherIdentification1();
    }

    /**
     * Create an instance of {@link Pagination }
     */
    public Pagination createPagination() {
        return new Pagination();
    }

    /**
     * Create an instance of {@link CAMT053Party11Choice }
     */
    public CAMT053Party11Choice createCAMT053Party11Choice() {
        return new CAMT053Party11Choice();
    }

    /**
     * Create an instance of {@link CAMT053PartyIdentification43 }
     */
    public CAMT053PartyIdentification43 createCAMT053PartyIdentification43() {
        return new CAMT053PartyIdentification43();
    }

    /**
     * Create an instance of {@link CAMT053PaymentCard4 }
     */
    public CAMT053PaymentCard4 createCAMT053PaymentCard4() {
        return new CAMT053PaymentCard4();
    }

    /**
     * Create an instance of {@link CAMT053PaymentReturnReason2 }
     */
    public CAMT053PaymentReturnReason2 createCAMT053PaymentReturnReason2() {
        return new CAMT053PaymentReturnReason2();
    }

    /**
     * Create an instance of {@link PersonIdentification5 }
     */
    public PersonIdentification5 createPersonIdentification5() {
        return new PersonIdentification5();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link PlainCardData1 }
     */
    public PlainCardData1 createPlainCardData1() {
        return new PlainCardData1();
    }

    /**
     * Create an instance of {@link PointOfInteraction1 }
     */
    public PointOfInteraction1 createPointOfInteraction1() {
        return new PointOfInteraction1();
    }

    /**
     * Create an instance of {@link PointOfInteractionCapabilities1 }
     */
    public PointOfInteractionCapabilities1 createPointOfInteractionCapabilities1() {
        return new PointOfInteractionCapabilities1();
    }

    /**
     * Create an instance of {@link PointOfInteractionComponent1 }
     */
    public PointOfInteractionComponent1 createPointOfInteractionComponent1() {
        return new PointOfInteractionComponent1();
    }

    /**
     * Create an instance of {@link CAMT053PostalAddress6 }
     */
    public CAMT053PostalAddress6 createCAMT053PostalAddress6() {
        return new CAMT053PostalAddress6();
    }

    /**
     * Create an instance of {@link Price2 }
     */
    public Price2 createPrice2() {
        return new Price2();
    }

    /**
     * Create an instance of {@link PriceRateOrAmountChoice }
     */
    public PriceRateOrAmountChoice createPriceRateOrAmountChoice() {
        return new PriceRateOrAmountChoice();
    }

    /**
     * Create an instance of {@link Product2 }
     */
    public Product2 createProduct2() {
        return new Product2();
    }

    /**
     * Create an instance of {@link CAMT053ProprietaryAgent3 }
     */
    public CAMT053ProprietaryAgent3 createCAMT053ProprietaryAgent3() {
        return new CAMT053ProprietaryAgent3();
    }

    /**
     * Create an instance of {@link CAMT053ProprietaryBankTransactionCodeStructure1 }
     */
    public CAMT053ProprietaryBankTransactionCodeStructure1 createCAMT053ProprietaryBankTransactionCodeStructure1() {
        return new CAMT053ProprietaryBankTransactionCodeStructure1();
    }

    /**
     * Create an instance of {@link CAMT053ProprietaryDate2 }
     */
    public CAMT053ProprietaryDate2 createCAMT053ProprietaryDate2() {
        return new CAMT053ProprietaryDate2();
    }

    /**
     * Create an instance of {@link CAMT053ProprietaryParty3 }
     */
    public CAMT053ProprietaryParty3 createCAMT053ProprietaryParty3() {
        return new CAMT053ProprietaryParty3();
    }

    /**
     * Create an instance of {@link ProprietaryPrice2 }
     */
    public ProprietaryPrice2 createProprietaryPrice2() {
        return new ProprietaryPrice2();
    }

    /**
     * Create an instance of {@link ProprietaryQuantity1 }
     */
    public ProprietaryQuantity1 createProprietaryQuantity1() {
        return new ProprietaryQuantity1();
    }

    /**
     * Create an instance of {@link ProprietaryReference1 }
     */
    public ProprietaryReference1 createProprietaryReference1() {
        return new ProprietaryReference1();
    }

    /**
     * Create an instance of {@link CAMT053Purpose2Choice }
     */
    public CAMT053Purpose2Choice createCAMT053Purpose2Choice() {
        return new CAMT053Purpose2Choice();
    }

    /**
     * Create an instance of {@link Rate3 }
     */
    public Rate3 createRate3() {
        return new Rate3();
    }

    /**
     * Create an instance of {@link RateType4Choice }
     */
    public RateType4Choice createRateType4Choice() {
        return new RateType4Choice();
    }

    /**
     * Create an instance of {@link ReferredDocumentInformation3 }
     */
    public ReferredDocumentInformation3 createReferredDocumentInformation3() {
        return new ReferredDocumentInformation3();
    }

    /**
     * Create an instance of {@link ReferredDocumentType1Choice }
     */
    public ReferredDocumentType1Choice createReferredDocumentType1Choice() {
        return new ReferredDocumentType1Choice();
    }

    /**
     * Create an instance of {@link ReferredDocumentType2 }
     */
    public ReferredDocumentType2 createReferredDocumentType2() {
        return new ReferredDocumentType2();
    }

    /**
     * Create an instance of {@link RemittanceAmount2 }
     */
    public RemittanceAmount2 createRemittanceAmount2() {
        return new RemittanceAmount2();
    }

    /**
     * Create an instance of {@link CAMT053RemittanceInformation7 }
     */
    public CAMT053RemittanceInformation7 createCAMT053RemittanceInformation7() {
        return new CAMT053RemittanceInformation7();
    }

    /**
     * Create an instance of {@link CAMT053RemittanceLocation2 }
     */
    public CAMT053RemittanceLocation2 createCAMT053RemittanceLocation2() {
        return new CAMT053RemittanceLocation2();
    }

    /**
     * Create an instance of {@link CAMT053ReportEntry4 }
     */
    public CAMT053ReportEntry4 createCAMT053ReportEntry4() {
        return new CAMT053ReportEntry4();
    }

    /**
     * Create an instance of {@link ReportingSource1Choice }
     */
    public ReportingSource1Choice createReportingSource1Choice() {
        return new ReportingSource1Choice();
    }

    /**
     * Create an instance of {@link CAMT053ReturnReason5Choice }
     */
    public CAMT053ReturnReason5Choice createCAMT053ReturnReason5Choice() {
        return new CAMT053ReturnReason5Choice();
    }

    /**
     * Create an instance of {@link SecuritiesAccount13 }
     */
    public SecuritiesAccount13 createSecuritiesAccount13() {
        return new SecuritiesAccount13();
    }

    /**
     * Create an instance of {@link SecurityIdentification14 }
     */
    public SecurityIdentification14 createSecurityIdentification14() {
        return new SecurityIdentification14();
    }

    /**
     * Create an instance of {@link CAMT053StructuredRemittanceInformation9 }
     */
    public CAMT053StructuredRemittanceInformation9 createCAMT053StructuredRemittanceInformation9() {
        return new CAMT053StructuredRemittanceInformation9();
    }

    /**
     * Create an instance of {@link SupplementaryData1 }
     */
    public SupplementaryData1 createSupplementaryData1() {
        return new SupplementaryData1();
    }

    /**
     * Create an instance of {@link SupplementaryDataEnvelope1 }
     */
    public SupplementaryDataEnvelope1 createSupplementaryDataEnvelope1() {
        return new SupplementaryDataEnvelope1();
    }

    /**
     * Create an instance of {@link TaxAmount1 }
     */
    public TaxAmount1 createTaxAmount1() {
        return new TaxAmount1();
    }

    /**
     * Create an instance of {@link TaxAmountAndType1 }
     */
    public TaxAmountAndType1 createTaxAmountAndType1() {
        return new TaxAmountAndType1();
    }

    /**
     * Create an instance of {@link TaxAmountType1Choice }
     */
    public TaxAmountType1Choice createTaxAmountType1Choice() {
        return new TaxAmountType1Choice();
    }

    /**
     * Create an instance of {@link TaxAuthorisation1 }
     */
    public TaxAuthorisation1 createTaxAuthorisation1() {
        return new TaxAuthorisation1();
    }

    /**
     * Create an instance of {@link TaxCharges2 }
     */
    public TaxCharges2 createTaxCharges2() {
        return new TaxCharges2();
    }

    /**
     * Create an instance of {@link TaxInformation3 }
     */
    public TaxInformation3 createTaxInformation3() {
        return new TaxInformation3();
    }

    /**
     * Create an instance of {@link TaxParty1 }
     */
    public TaxParty1 createTaxParty1() {
        return new TaxParty1();
    }

    /**
     * Create an instance of {@link TaxParty2 }
     */
    public TaxParty2 createTaxParty2() {
        return new TaxParty2();
    }

    /**
     * Create an instance of {@link TaxPeriod1 }
     */
    public TaxPeriod1 createTaxPeriod1() {
        return new TaxPeriod1();
    }

    /**
     * Create an instance of {@link TaxRecord1 }
     */
    public TaxRecord1 createTaxRecord1() {
        return new TaxRecord1();
    }

    /**
     * Create an instance of {@link TaxRecordDetails1 }
     */
    public TaxRecordDetails1 createTaxRecordDetails1() {
        return new TaxRecordDetails1();
    }

    /**
     * Create an instance of {@link TechnicalInputChannel1Choice }
     */
    public TechnicalInputChannel1Choice createTechnicalInputChannel1Choice() {
        return new TechnicalInputChannel1Choice();
    }

    /**
     * Create an instance of {@link CAMT053TotalTransactions4 }
     */
    public CAMT053TotalTransactions4 createCAMT053TotalTransactions4() {
        return new CAMT053TotalTransactions4();
    }

    /**
     * Create an instance of {@link CAMT053TotalsPerBankTransactionCode3 }
     */
    public CAMT053TotalsPerBankTransactionCode3 createCAMT053TotalsPerBankTransactionCode3() {
        return new CAMT053TotalsPerBankTransactionCode3();
    }

    /**
     * Create an instance of {@link TrackData1 }
     */
    public TrackData1 createTrackData1() {
        return new TrackData1();
    }

    /**
     * Create an instance of {@link CAMT053TransactionAgents3 }
     */
    public CAMT053TransactionAgents3 createCAMT053TransactionAgents3() {
        return new CAMT053TransactionAgents3();
    }

    /**
     * Create an instance of {@link CAMT053TransactionDates2 }
     */
    public CAMT053TransactionDates2 createCAMT053TransactionDates2() {
        return new CAMT053TransactionDates2();
    }

    /**
     * Create an instance of {@link TransactionIdentifier1 }
     */
    public TransactionIdentifier1 createTransactionIdentifier1() {
        return new TransactionIdentifier1();
    }

    /**
     * Create an instance of {@link TransactionInterest3 }
     */
    public TransactionInterest3 createTransactionInterest3() {
        return new TransactionInterest3();
    }

    /**
     * Create an instance of {@link CAMT053TransactionParties3 }
     */
    public CAMT053TransactionParties3 createCAMT053TransactionParties3() {
        return new CAMT053TransactionParties3();
    }

    /**
     * Create an instance of {@link TransactionPrice3Choice }
     */
    public TransactionPrice3Choice createTransactionPrice3Choice() {
        return new TransactionPrice3Choice();
    }

    /**
     * Create an instance of {@link TransactionQuantities2Choice }
     */
    public TransactionQuantities2Choice createTransactionQuantities2Choice() {
        return new TransactionQuantities2Choice();
    }

    /**
     * Create an instance of {@link CAMT053TransactionReferences3 }
     */
    public CAMT053TransactionReferences3 createCAMT053TransactionReferences3() {
        return new CAMT053TransactionReferences3();
    }

    /**
     * Create an instance of {@link YieldedOrValueType1Choice }
     */
    public YieldedOrValueType1Choice createYieldedOrValueType1Choice() {
        return new YieldedOrValueType1Choice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.053.001.04", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
