//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.swift.xsd.camt_019_001;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for CAMT019RequestType2Choice complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CAMT019RequestType2Choice"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="PmtCtrl" type="{urn:swift:xsd:camt.019.001.04}RequestType1Code"/&gt;
 *           &lt;element name="Enqry" type="{urn:swift:xsd:camt.019.001.04}RequestType2Code"/&gt;
 *           &lt;element name="Prtry" type="{urn:swift:xsd:camt.019.001.04}GenericIdentification1CMA"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CAMT019RequestType2Choice", propOrder = {
        "pmtCtrl",
        "enqry",
        "prtry"
})
public class CAMT019RequestType2Choice {

    @XmlElement(name = "PmtCtrl")
    @XmlSchemaType(name = "string")
    protected RequestType1Code pmtCtrl;
    @XmlElement(name = "Enqry")
    @XmlSchemaType(name = "string")
    protected RequestType2Code enqry;
    @XmlElement(name = "Prtry")
    protected GenericIdentification1CMA prtry;

    /**
     * Gets the value of the pmtCtrl property.
     *
     * @return possible object is
     * {@link RequestType1Code }
     */
    public RequestType1Code getPmtCtrl() {
        return pmtCtrl;
    }

    /**
     * Sets the value of the pmtCtrl property.
     *
     * @param value allowed object is
     *              {@link RequestType1Code }
     */
    public void setPmtCtrl(RequestType1Code value) {
        this.pmtCtrl = value;
    }

    /**
     * Gets the value of the enqry property.
     *
     * @return possible object is
     * {@link RequestType2Code }
     */
    public RequestType2Code getEnqry() {
        return enqry;
    }

    /**
     * Sets the value of the enqry property.
     *
     * @param value allowed object is
     *              {@link RequestType2Code }
     */
    public void setEnqry(RequestType2Code value) {
        this.enqry = value;
    }

    /**
     * Gets the value of the prtry property.
     *
     * @return possible object is
     * {@link GenericIdentification1CMA }
     */
    public GenericIdentification1CMA getPrtry() {
        return prtry;
    }

    /**
     * Sets the value of the prtry property.
     *
     * @param value allowed object is
     *              {@link GenericIdentification1CMA }
     */
    public void setPrtry(GenericIdentification1CMA value) {
        this.prtry = value;
    }

}
