//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.swift.xsd.camt_019_001;

import com.cbl.cityrtgs.models.dto.message.RtgsDocument;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Document"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RtrBizDayInf" type="{urn:swift:xsd:camt.019.001.04}ReturnBusinessDayInformationV04CMA"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
        "rtrBizDayInf"
})
public class Document implements RtgsDocument {

    @XmlElement(name = "RtrBizDayInf", required = true)
    protected ReturnBusinessDayInformationV04CMA rtrBizDayInf;

    /**
     * Gets the value of the rtrBizDayInf property.
     *
     * @return possible object is
     * {@link ReturnBusinessDayInformationV04CMA }
     */
    public ReturnBusinessDayInformationV04CMA getRtrBizDayInf() {
        return rtrBizDayInf;
    }

    /**
     * Sets the value of the rtrBizDayInf property.
     *
     * @param value allowed object is
     *              {@link ReturnBusinessDayInformationV04CMA }
     */
    public void setRtrBizDayInf(ReturnBusinessDayInformationV04CMA value) {
        this.rtrBizDayInf = value;
    }

}
