//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.swift.xsd.camt_019_001;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ErrorHandling1Code.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ErrorHandling1Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="X020"/&gt;
 *     &lt;enumeration value="X030"/&gt;
 *     &lt;enumeration value="X050"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "ErrorHandling1Code")
@XmlEnum
public enum ErrorHandling1Code {

    @XmlEnumValue("X020")
    X_020("X020"),
    @XmlEnumValue("X030")
    X_030("X030"),
    @XmlEnumValue("X050")
    X_050("X050");
    private final String value;

    ErrorHandling1Code(String v) {
        value = v;
    }

    public static ErrorHandling1Code fromValue(String v) {
        for (ErrorHandling1Code c : ErrorHandling1Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
