//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.swift.xsd.camt_019_001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the swift.xsd.camt_019_001 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:swift:xsd:camt.019.001.04", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: swift.xsd.camt_019_001
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link BusinessDay1CMA }
     */
    public BusinessDay1CMA createBusinessDay1CMA() {
        return new BusinessDay1CMA();
    }

    /**
     * Create an instance of {@link BusinessDay2CMA }
     */
    public BusinessDay2CMA createBusinessDay2CMA() {
        return new BusinessDay2CMA();
    }

    /**
     * Create an instance of {@link BusinessDayReportOrError1ChoiceCMA }
     */
    public BusinessDayReportOrError1ChoiceCMA createBusinessDayReportOrError1ChoiceCMA() {
        return new BusinessDayReportOrError1ChoiceCMA();
    }

    /**
     * Create an instance of {@link BusinessDayReportOrError2ChoiceCMA }
     */
    public BusinessDayReportOrError2ChoiceCMA createBusinessDayReportOrError2ChoiceCMA() {
        return new BusinessDayReportOrError2ChoiceCMA();
    }

    /**
     * Create an instance of {@link ClosureReason2Choice }
     */
    public ClosureReason2Choice createClosureReason2Choice() {
        return new ClosureReason2Choice();
    }

    /**
     * Create an instance of {@link DateTimePeriodChoice }
     */
    public DateTimePeriodChoice createDateTimePeriodChoice() {
        return new DateTimePeriodChoice();
    }

    /**
     * Create an instance of {@link DateTimePeriodDetails }
     */
    public DateTimePeriodDetails createDateTimePeriodDetails() {
        return new DateTimePeriodDetails();
    }

    /**
     * Create an instance of {@link ErrorHandling1Choice }
     */
    public ErrorHandling1Choice createErrorHandling1Choice() {
        return new ErrorHandling1Choice();
    }

    /**
     * Create an instance of {@link ErrorHandling3 }
     */
    public ErrorHandling3 createErrorHandling3() {
        return new ErrorHandling3();
    }

    /**
     * Create an instance of {@link CAMT019GenericIdentification1 }
     */
    public CAMT019GenericIdentification1 createCAMT019GenericIdentification1() {
        return new CAMT019GenericIdentification1();
    }

    /**
     * Create an instance of {@link GenericIdentification1CMA }
     */
    public GenericIdentification1CMA createGenericIdentification1CMA() {
        return new GenericIdentification1CMA();
    }

    /**
     * Create an instance of {@link MarketInfrastructureIdentification1ChoiceCMA }
     */
    public MarketInfrastructureIdentification1ChoiceCMA createMarketInfrastructureIdentification1ChoiceCMA() {
        return new MarketInfrastructureIdentification1ChoiceCMA();
    }

    /**
     * Create an instance of {@link CAMT019MessageHeader3CMA }
     */
    public CAMT019MessageHeader3CMA createCAMT019MessageHeader3CMA() {
        return new CAMT019MessageHeader3CMA();
    }

    /**
     * Create an instance of {@link OriginalBusinessQuery1CMA }
     */
    public OriginalBusinessQuery1CMA createOriginalBusinessQuery1CMA() {
        return new OriginalBusinessQuery1CMA();
    }

    /**
     * Create an instance of {@link CAMT019RequestType2Choice }
     */
    public CAMT019RequestType2Choice createCAMT019RequestType2Choice() {
        return new CAMT019RequestType2Choice();
    }

    /**
     * Create an instance of {@link ReturnBusinessDayInformationV04CMA }
     */
    public ReturnBusinessDayInformationV04CMA createReturnBusinessDayInformationV04CMA() {
        return new ReturnBusinessDayInformationV04CMA();
    }

    /**
     * Create an instance of {@link SystemAvailabilityAndEvents1CMA }
     */
    public SystemAvailabilityAndEvents1CMA createSystemAvailabilityAndEvents1CMA() {
        return new SystemAvailabilityAndEvents1CMA();
    }

    /**
     * Create an instance of {@link SystemClosure1 }
     */
    public SystemClosure1 createSystemClosure1() {
        return new SystemClosure1();
    }

    /**
     * Create an instance of {@link SystemEvent2CMA }
     */
    public SystemEvent2CMA createSystemEvent2CMA() {
        return new SystemEvent2CMA();
    }

    /**
     * Create an instance of {@link SystemEventType2ChoiceCMA }
     */
    public SystemEventType2ChoiceCMA createSystemEventType2ChoiceCMA() {
        return new SystemEventType2ChoiceCMA();
    }

    /**
     * Create an instance of {@link SystemIdentification2ChoiceCMA }
     */
    public SystemIdentification2ChoiceCMA createSystemIdentification2ChoiceCMA() {
        return new SystemIdentification2ChoiceCMA();
    }

    /**
     * Create an instance of {@link SystemStatus1 }
     */
    public SystemStatus1 createSystemStatus1() {
        return new SystemStatus1();
    }

    /**
     * Create an instance of {@link SystemStatus1CMA }
     */
    public SystemStatus1CMA createSystemStatus1CMA() {
        return new SystemStatus1CMA();
    }

    /**
     * Create an instance of {@link SystemStatus1Choice }
     */
    public SystemStatus1Choice createSystemStatus1Choice() {
        return new SystemStatus1Choice();
    }

    /**
     * Create an instance of {@link SystemStatus1ChoiceCMA }
     */
    public SystemStatus1ChoiceCMA createSystemStatus1ChoiceCMA() {
        return new SystemStatus1ChoiceCMA();
    }

    /**
     * Create an instance of {@link TimePeriodDetails }
     */
    public TimePeriodDetails createTimePeriodDetails() {
        return new TimePeriodDetails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = "urn:swift:xsd:camt.019.001.04", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
