//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.swift.xsd.camt_019_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReturnBusinessDayInformationV04CMA complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ReturnBusinessDayInformationV04CMA"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MsgHdr" type="{urn:swift:xsd:camt.019.001.04}CAMT019MessageHeader3CMA"/&gt;
 *         &lt;element name="RptOrErr" type="{urn:swift:xsd:camt.019.001.04}BusinessDayReportOrError1ChoiceCMA"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReturnBusinessDayInformationV04CMA", propOrder = {
        "msgHdr",
        "rptOrErr"
})
public class ReturnBusinessDayInformationV04CMA {

    @XmlElement(name = "MsgHdr", required = true)
    protected CAMT019MessageHeader3CMA msgHdr;
    @XmlElement(name = "RptOrErr", required = true)
    protected BusinessDayReportOrError1ChoiceCMA rptOrErr;

    /**
     * Gets the value of the msgHdr property.
     *
     * @return possible object is
     * {@link CAMT019MessageHeader3CMA }
     */
    public CAMT019MessageHeader3CMA getMsgHdr() {
        return msgHdr;
    }

    /**
     * Sets the value of the msgHdr property.
     *
     * @param value allowed object is
     *              {@link CAMT019MessageHeader3CMA }
     */
    public void setMsgHdr(CAMT019MessageHeader3CMA value) {
        this.msgHdr = value;
    }

    /**
     * Gets the value of the rptOrErr property.
     *
     * @return possible object is
     * {@link BusinessDayReportOrError1ChoiceCMA }
     */
    public BusinessDayReportOrError1ChoiceCMA getRptOrErr() {
        return rptOrErr;
    }

    /**
     * Sets the value of the rptOrErr property.
     *
     * @param value allowed object is
     *              {@link BusinessDayReportOrError1ChoiceCMA }
     */
    public void setRptOrErr(BusinessDayReportOrError1ChoiceCMA value) {
        this.rptOrErr = value;
    }

}
