//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.swift.xsd.camt_019_001;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for SystemStatus1ChoiceCMA complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SystemStatus1ChoiceCMA"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Cd" type="{urn:swift:xsd:camt.019.001.04}SystemStatus2Code"/&gt;
 *         &lt;element name="Prtry" type="{urn:swift:xsd:camt.019.001.04}GenericIdentification1CMA" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemStatus1ChoiceCMA", propOrder = {
        "cd",
        "prtry"
})
public class SystemStatus1ChoiceCMA {

    @XmlElement(name = "Cd", required = true)
    @XmlSchemaType(name = "string")
    protected SystemStatus2Code cd;
    @XmlElement(name = "Prtry")
    protected GenericIdentification1CMA prtry;

    /**
     * Gets the value of the cd property.
     *
     * @return possible object is
     * {@link SystemStatus2Code }
     */
    public SystemStatus2Code getCd() {
        return cd;
    }

    /**
     * Sets the value of the cd property.
     *
     * @param value allowed object is
     *              {@link SystemStatus2Code }
     */
    public void setCd(SystemStatus2Code value) {
        this.cd = value;
    }

    /**
     * Gets the value of the prtry property.
     *
     * @return possible object is
     * {@link GenericIdentification1CMA }
     */
    public GenericIdentification1CMA getPrtry() {
        return prtry;
    }

    /**
     * Sets the value of the prtry property.
     *
     * @param value allowed object is
     *              {@link GenericIdentification1CMA }
     */
    public void setPrtry(GenericIdentification1CMA value) {
        this.prtry = value;
    }

}
