//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.swift.xsd.camt_019_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SystemStatus1 complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SystemStatus1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Sts" type="{urn:swift:xsd:camt.019.001.04}SystemStatus1Choice"/&gt;
 *         &lt;element name="VldtyTm" type="{urn:swift:xsd:camt.019.001.04}DateTimePeriodChoice" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemStatus1", propOrder = {
        "sts",
        "vldtyTm"
})
public class SystemStatus1 {

    @XmlElement(name = "Sts", required = true)
    protected SystemStatus1Choice sts;
    @XmlElement(name = "VldtyTm")
    protected DateTimePeriodChoice vldtyTm;

    /**
     * Gets the value of the sts property.
     *
     * @return possible object is
     * {@link SystemStatus1Choice }
     */
    public SystemStatus1Choice getSts() {
        return sts;
    }

    /**
     * Sets the value of the sts property.
     *
     * @param value allowed object is
     *              {@link SystemStatus1Choice }
     */
    public void setSts(SystemStatus1Choice value) {
        this.sts = value;
    }

    /**
     * Gets the value of the vldtyTm property.
     *
     * @return possible object is
     * {@link DateTimePeriodChoice }
     */
    public DateTimePeriodChoice getVldtyTm() {
        return vldtyTm;
    }

    /**
     * Sets the value of the vldtyTm property.
     *
     * @param value allowed object is
     *              {@link DateTimePeriodChoice }
     */
    public void setVldtyTm(DateTimePeriodChoice value) {
        this.vldtyTm = value;
    }

}
