//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.swift.xsd.camt_019_001;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SystemClosureReason1Code.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SystemClosureReason1Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BHOL"/&gt;
 *     &lt;enumeration value="SMTN"/&gt;
 *     &lt;enumeration value="NOOP"/&gt;
 *     &lt;enumeration value="RCVR"/&gt;
 *     &lt;enumeration value="ADTW"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "SystemClosureReason1Code")
@XmlEnum
public enum SystemClosureReason1Code {

    BHOL,
    SMTN,
    NOOP,
    RCVR,
    ADTW;

    public static SystemClosureReason1Code fromValue(String v) {
        return valueOf(v);
    }

    public String value() {
        return name();
    }

}
