//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.swift.xsd.camt_019_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SystemIdentification2ChoiceCMA complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SystemIdentification2ChoiceCMA"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="MktInfrstrctrId" type="{urn:swift:xsd:camt.019.001.04}MarketInfrastructureIdentification1ChoiceCMA"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemIdentification2ChoiceCMA", propOrder = {
        "mktInfrstrctrId"
})
public class SystemIdentification2ChoiceCMA {

    @XmlElement(name = "MktInfrstrctrId")
    protected MarketInfrastructureIdentification1ChoiceCMA mktInfrstrctrId;

    /**
     * Gets the value of the mktInfrstrctrId property.
     *
     * @return possible object is
     * {@link MarketInfrastructureIdentification1ChoiceCMA }
     */
    public MarketInfrastructureIdentification1ChoiceCMA getMktInfrstrctrId() {
        return mktInfrstrctrId;
    }

    /**
     * Sets the value of the mktInfrstrctrId property.
     *
     * @param value allowed object is
     *              {@link MarketInfrastructureIdentification1ChoiceCMA }
     */
    public void setMktInfrstrctrId(MarketInfrastructureIdentification1ChoiceCMA value) {
        this.mktInfrstrctrId = value;
    }

}
