//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:21:52 AM BDT 
//


package iso20022.swift.xsd.camt_019_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SystemClosure1 complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SystemClosure1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Prd" type="{urn:swift:xsd:camt.019.001.04}DateTimePeriodChoice" minOccurs="0"/&gt;
 *         &lt;element name="Rsn" type="{urn:swift:xsd:camt.019.001.04}ClosureReason2Choice"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemClosure1", propOrder = {
        "prd",
        "rsn"
})
public class SystemClosure1 {

    @XmlElement(name = "Prd")
    protected DateTimePeriodChoice prd;
    @XmlElement(name = "Rsn", required = true)
    protected ClosureReason2Choice rsn;

    /**
     * Gets the value of the prd property.
     *
     * @return possible object is
     * {@link DateTimePeriodChoice }
     */
    public DateTimePeriodChoice getPrd() {
        return prd;
    }

    /**
     * Sets the value of the prd property.
     *
     * @param value allowed object is
     *              {@link DateTimePeriodChoice }
     */
    public void setPrd(DateTimePeriodChoice value) {
        this.prd = value;
    }

    /**
     * Gets the value of the rsn property.
     *
     * @return possible object is
     * {@link ClosureReason2Choice }
     */
    public ClosureReason2Choice getRsn() {
        return rsn;
    }

    /**
     * Sets the value of the rsn property.
     *
     * @param value allowed object is
     *              {@link ClosureReason2Choice }
     */
    public void setRsn(ClosureReason2Choice value) {
        this.rsn = value;
    }

}
